export const DAILY_TASKS_DATA_REQUEST = 'DAILY_TASKS_DATA_REQUEST'
export const DAILY_TASKS_DATA_RECEIVE = 'DAILY_TASKS_DATA_RECEIVE'
export const DAILY_TASKS_PROCESS_UPDATE = 'DAILY_TASKS_PROCESS_UPDATE'

export const DAILY_TASK_VALUE_ADD = 'DAILY_TASK_VALUE_ADD'
export const DAILY_TASK_REWARDED = 'DAILY_TASK_REWARDED'

export const DAILY_TASKS_SEEN = 'DAILY_TASKS_SEEN'
export const DAILY_TASK_FINISHED = 'DAILY_TASK_FINISHED'
