export const AnalyticsEvents = {
    BUTTON_CLICK: 'button_click',
    SCREEN_OPEN: 'screen_open',
    LOAD_START: 'load_start',
    LOAD_COMPLETE: 'load_complete',
    APP_READY: 'app_ready',
    TUTORIAL_BEGIN: 'tutorial_begin',
    TUTORIAL_STEP: 'tutorial_step',
    TUTORIAL_COMPLETE: 'tutorial_complete',
    MATCH_START: 'match_start',
    MATCH_RESCUE: 'match_rescue',
    MATCH_END: 'match_end',
    LEVEL_START: 'level_start',
    LEVEL_RESCUE: 'level_rescue',
    LEVEL_END: 'level_end',
    SHARE: 'share',
    MESSAGE: 'message',
    INVITE: 'invite',
    SHORTCUT_CREATE: 'shortcut_create',
    SHORTCUT_CREATE_POPUP: 'shortcut_create_popup',
    BOT_SUBSCRIBE: 'bot_subscribe',
    BOT_SUBSCRIBE_POPUP: 'bot_subscribe_popup',
    AD_SHOW: 'ad_show',
    AD_SHOW_FAILED: 'ad_show_failed',
    NEW_USER: 'new_user',
    AD_IMPRESSION: 'ad_impression',
    JOIN_GROUP: 'join_group',
    DAILY_CHALLENGE_BEGIN: 'daily_challenge_begin',
    DAILY_CHALLENGE_FAIL: 'daily_challenge_fail',
    DAILY_CHALLENGE_END: 'daily_challenge_end',

    // Tournaments
    TOURNAMENT_SHARE: 'tournament_share',
    TOURNAMENT_CREATE: 'tournament_create',
    TOURNAMENT_POST_SCORE: 'tournament_post_score',
}
