/**
 * CONTEXT
 */
export const CONTEXT_RECEIVED = 'CONTEXT_RECEIVED'
export const CONTEXT_PROCESSED = 'CONTEXT_PROCESSED'
export const CONTEXT_GAME_MODE_DETECTED = 'CONTEXT_GAME_MODE_DETECTED'

/**
 * MESSAGES
 */
export const MESSAGES_SENT_UPDATE = 'MESSAGES_SENT_UPDATE'
export const MESSAGES_SENT_REMOVE = 'MESSAGES_SENT_REMOVE'

/**
 * SCENE
 */
export const SCENE_KEY_UPDATE = 'SCENE_KEY_UPDATE'
