import SCREEN_EVENTS from '@/plugins/screen/constants/events'

export const ScreenKeys = {
    ALERT_SCREEN: 'ALERT_SCREEN',
    NOTIFY_SCREEN: 'NOTIFY_SCREEN',
    REWARD_SCREEN: 'REWARD_SCREEN',
    RESCUE_SCREEN: 'RESCUE_SCREEN',
    SETTINGS_SCREEN: 'SETTINGS_SCREEN',
    BEST_SCORE_SCREEN: 'BEST_SCORE_SCREEN',
    RESULT_SCREEN: 'RESULT_SCREEN',
    DAILY_REWARD_SCREEN: 'DAILY_REWARD_SCREEN',
    DAILY_MISSIONS_SCREEN: 'DAILY_MISSIONS_SCREEN',
    GAME_OVER_SCREEN: 'GAME_OVER_SCREEN',
    TUTORIAL_PLAY_SCREEN: 'TUTORIAL_PLAY_SCREEN',
    LEADER_BOARD_SCREEN: 'LEADER_BOARD_SCREEN',
    MINI_JOURNEY_SCREEN: 'MINI_JOURNEY_SCREEN',
    DAILY_CHALLENGE_SCREEN: 'DAILY_CHALLENGE_SCREEN',
    YOUR_SCORE_SCREEN: 'YOUR_SCORE_SCREEN',
    LEVEL_SCREEN: 'LEVEL_SCREEN',
    MISSION_SCORE_COMPLETE_SCREEN: 'MISSION_SCORE_COMPLETE_SCREEN',
    MISSION_COLLECTION_COMPLETE_SCREEN: 'MISSION_COLLECTION_COMPLETE_SCREEN',
    MISSION_FAIL_SCREEN: 'MISSION_FAIL_SCREEN',
    COLLISION_COMPLETED_SCREEN: 'COLLISION_COMPLETED_SCREEN',
    NO_SPACE_LEFT_SCREEN: 'NO_SPACE_LEFT_SCREEN',
    SCORE_REACHED_SCREEN: 'SCORE_REACHED_SCREEN',
    NEXT_TARGET_SCORE_SCREEN: 'NEXT_TARGET_SCORE_SCREEN',
    COLLECTION_ITEMS_SCREEN: 'COLLECTION_ITEMS_SCREEN',
    TARGET_SCORE_SCREEN: 'TARGET_SCORE_SCREEN',
    LUCKY_REWARD_SCREEN: 'LUCKY_REWARD_SCREEN',
    CLAIM_HEART_SCREEN: 'CLAIM_HEART_SCREEN',
    START_OVER_SCREEN: 'START_OVER_SCREEN',
}

export const ScreenDepth = {
    SCREEN: 200,
    POPUP: 300,
    PRIORITY: 999,
}

export const ScreenEvents = SCREEN_EVENTS
