export const MISSIONS_DATA_REQUEST = 'MISSIONS_DATA_REQUEST'
export const MISSIONS_DATA_RECEIVE = 'MISSIONS_DATA_RECEIVE'

export const MISSION_START = 'MISSION_START'
export const MISSION_UPDATE = 'MISSION_UPDATE'
export const MISSION_COMPLETED = 'MISSION_COMPLETED'
