export const DAILY_CHALLENGE_REQUEST = 'DAILY_CHALLENGE_REQUEST'
export const DAILY_CHALLENGE_UPDATE = 'DAILY_CHALLENGE_UPDATE'
export const DAILY_CHALLENGE_TIME_PLAY_UPDATE = 'DAILY_CHALLENGE_TIME_PLAY_UPDATE'
