const defaultConfig = {
    active: true,
    blendMode: 0,
    collideBottom: true,
    collideLeft: true,
    collideRight: true,
    collideTop: true,
    frequency: 0,
    gravityX: 0,
    gravityY: 0,
    maxParticles: 0,
    name: '',
    on: true,
    particleBringToTop: true,
    radial: true,
    timeScale: 1,
    trackVisible: false,
    visible: true,
    accelerationX: 0,
    accelerationY: 0,
    angle: { min: 0, max: 360 },
    alpha: 1,
    bounce: 0,
    delay: 0,
    lifespan: 1000,
    maxVelocityX: 10000,
    maxVelocityY: 10000,
    moveToX: 0,
    moveToY: 0,
    quantity: 1,
    rotate: 0,
    scaleX: 1,
    speedX: 0,
    speedY: 0,
    tint: 16777215,
    x: 0,
    y: 0,
}

export default defaultConfig
